
name: deploy-to-aws-eb

on:
  push:
    branches: [ aws ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"
          
      - name: Build with Maven
        run:  mvn clean install --% -Dmaven.test.skip=true -Paws 

      - name: Upload package to S3 bucket
        run: aws s3 cp target/forumX_user-0.0.1-SNAPSHOT.jar s3://forumx-user/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name forumx-user \
          --source-bundle S3Bucket="forumx-user",S3Key="forumX_user-0.0.1-SNAPSHOT.jar" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name forumx-user-env --version-label "ver-${{ github.sha }}"
